
/*  BARCODE ACTIONS */

export const GET_BARCODE_DATA = 'GET_BARCODE_DATA';
export const GET_BARCODE_LABEL_TYPE = 'GET_BARCODE_LABEL_TYPE';
export const GET_BARCODE_SOURCE = 'GET_BARCODE_SOURCE';
export const GET_ENUMERATED_SCANNERS = 'GET_ENUMERATED_SCANNERS';